### ISSUE TITLE
Level wise linkedlist

### ISSUE THREAD

**Issue by rishabh3112** [rishabh3112/Binary-Trees#16]
### Question
Given a binary tree, write code to create a separate linked list for each level. You need to return the array which contains head of each level linked list.

**Input format**
```
Elements in level order form (separated by space).
If any node does not have left or right child, take -1 in its place.
```
**Output format**
```
Each level linked list is printed in new line (elements separated by space).
```

**Comment by ShaguftaShahroz** [comment]
import java.util.*;

public class Solution {
	/*
	 * BinaryTreeNode class
	 * 
	 * class BinaryTreeNode<T> 
	 * { 
	 * 		T data; 
	 * 		BinaryTreeNode<T> left; 
	 * 		BinaryTreeNode<T> right;
	 *		public BinaryTreeNode(T data) 
	 *		{
	 *  		this.data = data; 
	 *  	} 
	 *  }
	 */
	/*
	 * LinkedListNode Class
	 * class LinkedListNode<T> 
	 * { 
	 * 		T data; 
	 * 		LinkedListNode<T> next;
	 * 		public LinkedListNode(T data) 	
	 * 		{
	 *  		this.data = data; 
	 *  	} 
	 *  }
	 */
	public static ArrayList<LinkedListNode<Integer>> constructLinkedListForEachLevel(BinaryTreeNode<Integer> root){
		ArrayList<LinkedListNode<Integer>> ans = new ArrayList<>();
        if(root == null)
            return ans;
        Queue<BinaryTreeNode<Integer>> q = new LinkedList<>();
        q.offer(root);
        while(!q.isEmpty())
        {
            int size = q.size();
            LinkedListNode<Integer> level = new LinkedListNode<>(0);
            LinkedListNode<Integer> head = null;
            while(size-- > 0)
            {
                BinaryTreeNode<Integer> temp = q.poll();
                if(temp.left != null)
                    q.add(temp.left);
                if(temp.right != null)
                    q.add(temp.right);
                if(head == null)
                {
                    LinkedListNode<Integer> newNode = new LinkedListNode<>(temp.data);
                    level=newNode;
                    head = newNode;
                }
                else
                {
                    LinkedListNode<Integer> newNode = new LinkedListNode<>(temp.data);
                    level.next=newNode;
                    level=level.next;
                }
            }
            ans.add(head);
        }
        return ans;
	}

}
